@startuml getAllParksClientStreaming
User -> ParkGrpcService: Sends RPC Request
loop While new Request Recieved
ParkGrpcService -> ParkService: Requests Parks
ParkService -> ParkRepository: Get All Parks
ParkService <- ParkRepository: Returns Found Parks
ParkGrpcService <- ParkService: Returns Parks
ParkGrpcService -> Mapper: Maps Parks to Proto ListPark
ParkGrpcService -> ParkGrpcService: Applies FieldMask
end
User <- ParkGrpcService: Returns Result
@enduml