@startuml getAllParksServerStreaming
User -> ParkGrpcService: Sends RPC Request
ParkGrpcService -> ParkService: Requests Parks
ParkService -> ParkRepository: Get All Parks
ParkService <- ParkRepository: Returns Found Parks
ParkGrpcService <- ParkService: Returns Parks
ParkGrpcService -> Mapper: Maps Parks to Proto ListPark
ParkGrpcService -> ParkGrpcService: Applies FieldMask
User <- ParkGrpcService: Writes Async Result
@enduml