@startuml

package "Backoffice Architecture" {
    package "API"{
        package "Grpc"{
            [gRPCControllers]
        }
        package "Protos"{
            [Protobuf Objects]
        }
        package "ProtoMap"{
            [Protobuf Mappers]
        }
    }
    package "Application" {
        package "Services"{
            [BackofficeServices]
        }
        package "Mappers"{
            [BackofficeMappers]
        }
    }
    package "Core" {
        package "Domain"{
            [Entities]
        }
        package "Dtos"{
            [DTOs]
        }
        package "IRepositories"{
            [RepositoryInterfaces]
        }
        package "IServices"{
            [ServiceInterfaces]
        }
    }
    package "DatabaseManagement"{
        [Queries]
    }
    package "Infrastructure"{
        [Repositories]
    }
    API --> Application
    Application --> Core
    Core --> DatabaseManagement
    Core --> Infrastructure
}

@enduml
